version: '2'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      - MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      - MINIO_REGION=us-east-1
      - MINIO_DOMAIN=localhost
      - MINIO_BROWSER=off
    command: server /export
    volumes:
      - ./config:/root/.minio
      - ./data:/data
  mc:
    image: minio/mc:latest
    depends_on:
      - minio
    container_name: mc
    environment:
      - MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      - MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add s3 http://change-to-your-domain.com:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY}) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb s3/change-to-bucket-name --region us-east-1;
      /usr/bin/mc policy set public s3/change-to-bucket-name;
      exit 0;
      "
